language: php

php:
  - 5.4        
  - 5.5
  - 5.6
  - 7
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer dump-autoload -o

script:
  - bin/kahlan --coverage=4 --reporter=verbose

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: 7.1
